---
# tasks file for packages
- name: update system
  apt:
    update_cache: yes
    upgrade: dist
- name: install packages we don't need any customization for
  package:
    name: "{{ item }}"
  with_items:
    - "{{ packages_list }}"
