---
- name: Install xorg packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - xserver-xorg-core
    - xserver-xorg-input-evdev
    - x11-xserver-utils
    - xinit
    - xfonts-100dpi
    - xfonts-75dpi
    - xfonts-terminus
- name: Ensure .fonts folder exists
  file:
    path: "/home/{{ user.name }}/.fonts"
    state: directory
- name: Install Inconsolata font
  copy:
    src: "files/fonts/Inconsolata for Powerline.otf"
    dest: "/home/{{ user.name }}/.fonts/Inconsolata for Powerline.otf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
