---
- name: set up data container for wekan
  docker_container:
    name: wekandata
    image: busybox
    state: present
    volumes: /data

- name: wekan mongodb container
  docker_container:
    name: wekandb
    image: "mongo:{{ wekan_mongo_tag }}"
    state: started
    volumes_from:
    - wekandata

- name: wekan container
  docker_container:
    name: wekan
    image: "wekanteam/wekan:{{ wekan_tag }}"
    state: started
    links:
    - wekandb
    ports:
    - "{{ wekan_port }}:80"
    env:
        MONGO_URL: mongodb://wekandb/wekan
        ROOT_URL: "{{ wekan_root_url }}"
