---
- name: Install chrome apt-key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    id: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991
- name: Install google-chrome-stable
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  creates: /etc/apt/sources.list.d/google-chrome.list
