---
- name: check if discord is already installed
  command: dpkg-query -W discord
  register: discord_installed
  failed_when: discord_installed.rc > 1
  changed_when: discord_installed.rc == 1
- name: Install discord
  apt:
    deb: "{{ discord_package_url }}"
  when: discord_installed.rc == 1
